const DASHBOARD_PIN='change-me';
const auth=document.querySelector('#auth-gate');
if(sessionStorage.getItem('orbit-auth')==='ok')auth.remove();
document.querySelector('#auth-form').addEventListener('submit',e=>{e.preventDefault();if(document.querySelector('#auth-pin').value===DASHBOARD_PIN){sessionStorage.setItem('orbit-auth','ok');auth.remove();}else document.querySelector('#auth-error').classList.remove('hidden');});
const markets=[['Bitcoin','BTC / USD','crypto','₿','#f5ac56','64,525.00','+2.34%'],['Ethereum','ETH / USD','crypto','Ξ','#a5b4fc','3,482.60','+1.82%'],['Euro / US Dollar','EUR / USD','forex','€','#7dd3fc','1.08565','+0.28%'],['British Pound / USD','GBP / USD','forex','£','#c4b5fd','1.27142','−0.16%']];
function renderMarkets(filter='all'){document.querySelector('#market-grid').innerHTML=markets.filter(m=>filter==='all'||m[2]===filter).map(m=>`<article class="bg-[#10161e] p-5"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full text-xl" style="color:${m[4]};background:${m[4]}15">${m[3]}</span><div><h3 class="text-xs text-white">${m[1]}</h3><p class="mt-1 text-[10px] text-slate-500">${m[0]}</p></div></div><div class="mt-5 flex justify-between"><div><p class="text-lg text-white">${m[5]}</p><p class="mt-1 text-xs ${m[6].startsWith('+')?'text-emerald-400':'text-rose-400'}">${m[6]} <span class="text-slate-600">24h</span></p></div><svg viewBox="0 0 90 30" class="h-10 w-24" aria-hidden="true"><path d="${m[6].startsWith('+')?'M0 25 L10 20 20 23 30 12 40 18 50 9 60 14 70 4 80 7 90 2':'M0 3 L10 8 20 5 30 12 40 10 50 17 60 13 70 21 80 19 90 26'}" fill="none" stroke="${m[6].startsWith('+')?'#34d399':'#fb7185'}" stroke-width="1.5"/></svg></div></article>`).join('');}
function renderChart(period){const seed={'1D':3,'1W':7,'1M':11,'ALL':17}[period];const pts=Array.from({length:65},(_,i)=>[20+i*10.6,211-i*2.5+Math.sin(i*1.6+seed)*9+Math.sin(i*.43)*15]);const line=pts.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ');const labels={'1D':['00:00','04:00','08:00','12:00','16:00','20:00'],'1W':['Mon','Tue','Wed','Thu','Fri','Sun'],'1M':['01 Sep','06 Sep','11 Sep','16 Sep','21 Sep','26 Sep'],'ALL':['Apr','May','Jun','Jul','Aug','Sep']}[period];document.querySelector('#chart').innerHTML=`<defs><linearGradient id="fade" x2="0" y2="1"><stop stop-color="#bef264" stop-opacity=".16"/><stop offset="1" stop-color="#bef264" stop-opacity="0"/></linearGradient></defs>${[30,80,130,180,230].map((y,i)=>`<line x1="20" y1="${y}" x2="715" y2="${y}" stroke="#ffffff08" stroke-dasharray="4 5"/><text x="731" y="${y+4}" fill="#596579" font-size="10">${['10,600','10,450','10,300','10,150','10,000'][i]}</text>`).join('')}<path d="${line} L698.4,230 L20,230 Z" fill="url(#fade)"/><path d="${line}" stroke="#bef264" stroke-width="2.3" fill="none"/>${labels.map((l,i)=>`<text x="${20+i*133}" y="258" fill="#596579" font-size="10">${l}</text>`).join('')}`;}
for(const kind of ['period','filter'])document.querySelectorAll(`[data-${kind}]`).forEach(button=>{button.setAttribute('aria-pressed',String(button.classList.contains('selected')));button.addEventListener('click',()=>{document.querySelectorAll(`[data-${kind}]`).forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});(kind==='period'?renderChart:renderMarkets)(button.dataset[kind]);});});
document.querySelectorAll('[data-settings]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#settings').showModal()));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
document.querySelector('#connect').addEventListener('click',()=>document.querySelector('#connection').showModal());
let toastTimer;function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),3500);}
document.querySelector('#settings-form').addEventListener('submit',e=>{e.preventDefault();const risk=Number(document.querySelector('#risk').value),limit=Number(document.querySelector('#limit').value);document.querySelector('#risk-label').textContent=risk.toFixed(2)+'%';document.querySelector('#limit-label').textContent=limit.toFixed(2)+'%';document.querySelector('#drawdown').style.width=Math.min(100,.42/limit*100)+'%';document.querySelector('#settings').close();toast('Preview updated. Bot configuration unchanged.');});
document.querySelector('#strategy-select').addEventListener('change',e=>{document.querySelector('#strategy-desc').textContent=e.target.value==='trend'?'EMA trend alignment, RSI momentum, and ATR stops.':'Donchian breakout + ADX strength + EMA regime + volatility filter.';toast('Preview selection only. Set STRATEGY in .env to change the bot.');});
document.querySelector('#export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({source:'ILLUSTRATIVE PREVIEW',connected:false,equity:10482.65,markets},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='orbit-preview.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Preview snapshot exported');});
function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('en-GB',{timeZone:'UTC'})+' UTC';}renderMarkets();renderChart('1M');clock();setInterval(clock,1000);
